-- * intended to define various roles by organizations as they relate to publications-- (publisher, broadcaster, etc.)

CREATE TABLE publications_organizations_roles (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * ROLE
  role VARCHAR (100) NOT NULL,
  description TEXT
);

-- Path: tables/primary/publications/publications_people.sql