/* This table tracks specific edition numbers within an editioned artwork.
Ownership associations to either a person or organization are tracked in the collections table. 
Other associations such as exhibitions, publications, etc. are made at the grandparent 'artwork' table. 
*/


CREATE TABLE artwork_edition (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * ARTWORK
  artwork_id INT NOT NULL REFERENCES artwork (id),
  type edition_category NOT NULL, -- ex: Trial Proof, Artist Proof, Edition, etc (see edition_category in enums.sql)
  number INT NOT NULL, -- used in combination with type to identify the edition number,
  signature signature_status DEFAULT 'front' NOT NULL,
  available BOOLEAN DEFAULT TRUE NOT NULL,
  status artwork_status DEFAULT 'in storage' NOT NULL, -- ex: in storage, on loan, sold, etc. (see artwork_status in enums.sql)
);

