-- For a PostgreSQL database
-- This file contains the SQL commands to create the database and tables


CREATE TABLE artwork (
  -- * METADATA
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * IDENTIFICATION
	catalog_number VARCHAR (14) NOT NULL UNIQUE,
	category artwork_category NOT NULL,
	title VARCHAR (255) DEFAULT 'Untitled' NOT NULL,
  series VARCHAR (255),

  -- * DATES
	date_started DATE,
	date_completed DATE NOT NULL,
	date_circa BOOLEAN DEFAULT FALSE,
  
  -- * MEASURMENTS
	height_cm DECIMAL(7, 2) CHECK (height_cm > 0) NOT NULL,
	width_cm DECIMAL (7, 2) CHECK (width_cm > 0) NOT NULL,
	depth_cm DECIMAL (7, 2),
	weight_kg DECIMAL (5, 2),
	height_in DECIMAL (8, 3),
	width_in DECIMAL (8, 3),
	depth_in DECIMAL (8, 3),
	weight_lbs DECIMAL (5, 2),
  pieces_number INT DEFAULT 1 CHECK (pieces_number >= 1),
	
  -- * MARKINGS
  signature signature_status DEFAULT 'unknown' NOT NULL, 
	
  -- * STATUS
  status artwork_status DEFAULT 'in storage' NOT NULL,
  available BOOLEAN DEFAULT TRUE NOT NULL,

	CHECK (
		(category = 'sculpture' AND depth_cm > 0) OR
		(category != 'Sculpture' AND (depth_cm IS NULL OR depth_cm > 0))
	)
);











CREATE TABLE collections (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  date_acquired DATE NOT NULL,

);

CREATE TABLE artwork_edition (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  artwork_id INT NOT NULL REFERENCES artwork (id),
  type edition_category NOT NULL,
  number INT NOT NULL,
  signature signature_status DEFAULT 'unknown' NOT NULL,
  available BOOLEAN DEFAULT TRUE NOT NULL,
)
