/* 
This table is used to store the summary of an editioned artwork. 
Associations to exhibits and publications are made to this table's parent--'artwork'.
Associations to publishers, fabricators, and printmakers are made with a join table connecting to organizations and people.
Associations to specific pieces within this edition are made are made to this table's child-- 'artwork_edition'.
Associations to the status and location of production materials (molds, negatives, printing plates, etc.) are made to this table's child-- 'edition_materials'.
*/


CREATE TABLE edition_summary (
  --* METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  --* EDITION INFO
  artwork_id INT NOT NULL REFERENCES artwork (id),
  status 
  ed_total INT NOT NULL, -- total number of editions
  ap_total INT NOT NULL, -- total number of artist proofs
  tp_total INT NOT NULL, -- total number of trial proofs
  pp_total INT NOT NULL, -- total number of printer proofs
  sp_total INT NOT NULL, -- total number of studio proofs
  hc_total INT NOT NULL, -- total number of hors de commerce proofs
  bt_total INT NOT NULL, -- total number of bon a tirer proofs

)
