--* ===== ENUMS =====
  \i enums/enums.sql
--* ===== TABLES =====
  \i tables/artworks/series.sql
  \i tables/artworks/artwork.sql 
  \i tables/people_organizations/organizations.sql
  \i tables/people_organizations/org_locations.sql
  \i tables/people_organizations/people.sql
  \i tables/people_organizations/people_organizations.sql 
  \i tables/people_organizations/artwork_models.sql 
  \i tables/people_organizations/contact_info/emails.sql 
  \i tables/people_organizations/contact_info/phone_numbers.sql 
  \i tables/people_organizations/contact_info/addresses.sql 
  \i tables/artworks/supports.sql
  \i tables/artworks/mediums.sql
  \i tables/artworks/artwork_support.sql
  \i tables/artworks/artwork_medium.sql
  \i tables/artworks/edition_meta.sql
  \i tables/artworks/edition.sql
  \i tables/artworks/damage.sql
  \i tables/artworks/artwork_location.sql
  \i tables/artworks/artwork_sequence.sql
  \i tables/exhibitions/exhibitions.sql 
  \i tables/exhibitions/exhibitions_people_roles.sql
  \i tables/exhibitions/exhibitions_artworks.sql
  \i tables/exhibitions/exhibitions_organizations.sql
  \i tables/exhibitions/exhibitions_people.sql 
  \i tables/publications/publications.sql
  \i tables/publications/publications_exhibitions.sql
  \i tables/publications/publications_people_roles.sql
  \i tables/publications/publications_people.sql 
  \i tables/publications/publications_organizations_roles.sql
  \i tables/publications/publications_organizations.sql
  \i tables/publications/publications_artworks.sql