--* This table joins artworks or editioned_artworks with a person or organization.  It is used to show ownership of original and editioned artworks by people or organizations.
--Path: tables/join/collections.sql

CREATE TABLE collections (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * JOIN
  artwork_id INT REFERENCES artwork (id),
  artwork_edition_id INT REFERENCES artwork_edition (id),
  person_id INT REFERENCES people (id),
  organization_id INT REFERENCES organizations (id),
  date_acquired DATE NOT NULL,

  --* VALIDATE- either artwork_id OR artwork_edition_id must be present
  CHECK (
    (artwork_id IS NOT NULL AND artwork_edition_id IS NULL) OR
    (artwork_id IS NULL AND artwork_edition_id IS NOT NULL)
  ),

  --* VALIDATE- either person_id OR organization_id must be present
  CHECK (
    (person_id IS NOT NULL AND organization_id IS NULL) OR
    (person_id IS NULL AND organization_id IS NOT NULL)
  )
)