/* 
This table joins the edition_summary table to either people or organizations
It's parent table contains details about the edition as a whole
This table associates people and organizations with the edition and their role in making the edition
 */

CREATE TABLE edition_summary_people (
  --* METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  --* EDITION INFO
  edition_summary_id INT NOT NULL REFERENCES edition_summary (id),
  people_id INT REFERENCES people (id),
  organization_id INT REFERENCES organizations (id),
  role edition_participant_role, -- ex: printer, publisher, etc. see edition_participant_role in enums.sql
  notes TEXT, -- any notes about the role of the person or organization in the edition
  --* VALIDATION -- either people_id or organization_id must be present
  CHECK (
    (people_id IS NOT NULL AND organization_id IS NULL)
    OR 
    (people_id IS NULL AND organization_id IS NOT NULL)
    )
);