--* This table joins tables 'onlinemedia' and 'people' when a person is associated in an online media. The 'role' field describes the association (author, interviewer, etc.)
-- Path: tables/join/onlinemedia_people.sql

CREATE TABLE onlinemedia_people (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * JOIN
  onlinemedia_id INT NOT NULL REFERENCES onlinemedia (id),
  people_id INT NOT NULL REFERENCES people (id),
  role VARCHAR (50) NOT NULL,
);

