--* This table is a join table between the tables 'onlinemedia' and 'artwork' when an artwork is featured in an online media.
-- Path: tables/join/onlinemedia_artwork.sql

CREATE TABLE onlinemedia_artwork (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * JOIN
  onlinemedia_id INT NOT NULL REFERENCES onlinemedia (id),
  artwork_id INT NOT NULL REFERENCES artwork (id),
)

