-- * This tables joins tables 'printmedia' and 'people' when a person is associated with a print media. The 'role' field describes the association (author, editor, interviewer, etc.)

CREATE TABLE printmedia_people (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * JOIN
  printmedia_id INT NOT NULL REFERENCES printmedia (id),
  people_id INT NOT NULL REFERENCES people (id),
  role VARCHAR (50) NOT NULL, -- author, editor, etc.
  )