--* This table joins tables 'printmedia' and 'artwork'. It is used when an artwork is mentioned or illustrated in a print media.
-- Path: tables/join/printmedia_artwork.sql

CREATE TABLE printmedia_artwork (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * JOIN
  printmedia_id INT NOT NULL REFERENCES printmedia (id),
  artwork_id INT NOT NULL REFERENCES artwork (id),
  page VARCHAR (50) NOT NULL,-- page number(s) the artwork appears on
  );