--* This table contains people.


CREATE TABLE people (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * PERSON
  first_name VARCHAR (100) NOT NULL,
  last_name VARCHAR (100) NOT NULL
);

-- Path: tables/primary/people_locations/people.sql
