--* This table is designed to store email addresses associated with either people or organizations.

CREATE TABLE emails (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  person_id INT REFERENCES people (id),
  organization_id INT REFERENCES organizations (id),

  -- * EMAIL
  email VARCHAR (255) NOT NULL UNIQUE,
  email_type VARCHAR (100) NOT NULL DEFAULT 'main',

CHECK (
  (CASE WHEN organization_id IS NOT NULL THEN 1 ELSE 0 END) +
  (CASE WHEN person_id IS NOT NULL THEN 1 ELSE 0 END) = 1
  )
);

-- Path: tables/people_organizations/contact_info/addresses.sql
