--* This table stores phone_numbers attached to either people or organizations.

CREATE TABLE phone_numbers (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  person_id INT REFERENCES people (id),
  organization_id INT REFERENCES organizations (id),

  -- * PHONE NUMBER
  phone_number VARCHAR (255) NOT NULL UNIQUE,
  phone_type VARCHAR (100) NOT NULL DEFAULT 'main',

CHECK (
  (CASE WHEN organization_id IS NOT NULL THEN 1 ELSE 0 END) +
  (CASE WHEN person_id IS NOT NULL THEN 1 ELSE 0 END) = 1
  )
);

-- Path: tables/people_organizations/contact_info/phone_numbers.sql