--* The artwork_location table keeps track of the locations of either an artwork or an editioned artwork, along with the organizations or individuals responsible for them. It includes metadata fields, location types (e.g., 'on loan', 'in storage'), time-stamps for when the artwork was moved in and out, and constraints to ensure that each record is associated with either an artwork or an edition, and either an organization or a person.

CREATE TYPE location_type AS ENUM ('on loan', 
  'on consignment', 
  'in storage', 
  'gift', 
  'sold',
  'donated',
  'in service',
  'destroyed' )

CREATE TABLE artwork_location (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artwork_id INT REFERENCES artworks (id),
  edition_id INT REFERENCES edition (id),
  organization_id INT REFERENCES organizations (id),
  person_id INT REFERENCES people (id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * LOCATION RELATIONSHIP
  location_type location_type NOT NULL DEFAULT 'in storage',
  out_date DATE NOT NULL,
  in_date DATE CHECK (in_date >= out_date),
  due_date DATE CHECK (due_date >= in_date),
  notes TEXT,



  -- Either an organization or a person must be present
CHECK (
  (CASE WHEN organization_id IS NOT NULL THEN 1 ELSE 0 END) +
  (CASE WHEN person_id IS NOT NULL THEN 1 ELSE 0 END) = 1
),

  -- Either an artwork or an edition must be present
CHECK (
  (CASE WHEN artwork_id IS NOT NULL THEN 1 ELSE 0 END) +
  (CASE WHEN edition_id IS NOT NULL THEN 1 ELSE 0 END) = 1
  )
);

-- Path: tables/artworks/artwork_location.sql


