-- * This table lists art mediums used with supports. It joins to the artwork table via the artwork_medium table.
CREATE TABLE mediums (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * MEDIUM
  name VARCHAR (255) NOT NULL UNIQUE,
  description TEXT
);

-- Path: tables/artworks/artwork_medium.sql

