/* TABLE singular_attributes holds the attributes that are unique to a specific piece 
whether that piece exists in the edition TABLE or artwork TABLE. */

CREATE TABLE singular_attributes (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  -- * SIGNATURES AND INSCRIPTIONS
  signature signature_status DEFAULT 'unknown' NOT NULL,
  signature_location VARCHAR(255),
  inscription VARCHAR(255),
  inscriptions_location VARCHAR(255),
  -- * STATUS
  available_exhibition BOOLEAN DEFAULT TRUE NOT NULL,
  available_purchase BOOLEAN DEFAULT TRUE NOT NULL,
  condition artwork_condition DEFAULT 'unknown' NOT NULL,
  storage_location VARCHAR(255),
  is_framed BOOLEAN DEFAULT FALSE NOT NULL
);

-- Path: tables/artworks/singular_attributes.sql
