--* This table lists supports art mediums are used on (eg. paper, canvas, etc.)
-- Joined to the artwork table via the artwork_support table.

CREATE TABLE supports (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * SUPPORT
  name VARCHAR (255) NOT NULL UNIQUE,
  description TEXT
);

-- Path: tables/artworks/supports.sql