--* This table stores information about valuations of an art piece.
--* The valuation can be for an artwork (artwork table) or an editioned piece (edition table).
--* The valuation can be from an organization (organization table) or a person (people table).
--* The valuation type can be from an auction, an exhibition, an appraisal, or another source.
--* The valuation's date and amount are also recorded


CREATE TYPE  val_type AS ENUM (
  'auction',  -- Amount sold at auction
  'exhibition', -- Amount listed during an exhibition
  'appraisal', -- Amount from an official appraisal
  'other'); -- Amount from another source

CREATE TABLE valuations (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  artwork_id INT REFERENCES artworks (id),
  edition_id INT REFERENCES edition (id),
  organization_id INT REFERENCES organizations (id),
  person_id INT REFERENCES people (id),

  amount NUMERIC (10, 2) NOT NULL,
  valuation_type VARCHAR (100),
  valuation_date DATE,
  valuation_description TEXT,

  -- Either an organization or a person must be present
CHECK (
  (CASE WHEN organization_id IS NOT NULL THEN 1 ELSE 0 END) +
  (CASE WHEN person_id IS NOT NULL THEN 1 ELSE 0 END) = 1
),

  -- Either an artwork or an edition must be present
CHECK (
  (CASE WHEN artwork_id IS NOT NULL THEN 1 ELSE 0 END) +
  (CASE WHEN edition_id IS NOT NULL THEN 1 ELSE 0 END) = 1
  )
);

-- Path: tables/artworks/valuations.sql

