--* This table stores the address information and must reference either a person ('people' table) or a location ('location' table).
-- Path: tables/primary/contact-info/address.sql
CREATE TABLE address (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * ADDRESS
  street VARCHAR (100) NOT NULL,
  city VARCHAR (50) NOT NULL,
  state VARCHAR (50) NOT NULL,
  zip VARCHAR (12) NOT NULL,
  country VARCHAR (50) NOT NULL,
  label VARCHAR (50),
  people_id INT REFERENCES people (id),
  location_id INT REFERENCES locations (id),
  -- * VALIDATION -- either people_id or location_id must be present
  CHECK (
    (people_id IS NOT NULL AND location_id IS NULL)
    OR 
    (people_id IS NULL AND location_id IS NOT NULL)
    )
);

