CREATE TABLE email (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * EMAIL
  email VARCHAR (255) NOT NULL,
  label VARCHAR (255),
  people_id INT REFERENCES people (id),
  location_id INT REFERENCES locations (id),
  CHECK (
    (people_id IS NOT NULL AND location_id IS NULL)
    OR 
    (people_id IS NULL AND location_id IS NOT NULL)
    )
);