--* This table holds the names of roles people can be involved with in exhibitions-- (e.g. curator, artist, etc.)

CREATE TABLE exhibitions_people_roles (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * ROLE
  role VARCHAR (100) NOT NULL,
  description TEXT
);

-- Path: tables/primary/exhibitions/exhibitions_people_roles.sql
