--* This table holds exhibition records

CREATE TYPE exhibition_type AS ENUM ('solo', 'group', 'benefit', 'auction', 'other');

CREATE TABLE exhibitions (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * EXHIBITION
  title VARCHAR (255) NOT NULL,
  type exhibition_type NOT NULL DEFAULT 'group',
  include_short_bib BOOLEAN NOT NULL DEFAULT TRUE,
  include_full_bib BOOLEAN NOT NULL DEFAULT TRUE
);
