CREATE TABLE broadcastmedia (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * BROADCAST MEDIA
  media_id INT NOT NULL REFERENCES media (id), -- the entity (media table) this broadcast is a part of
  type broadcast_type NOT NULL, -- the type of broadcast (see broadcast_type in enums.sql)
  show VARCHAR (255) NOT NULL, -- the name of the show
  broadcaster VARCHAR (255) NOT NULL, -- company or organization that broadcasted the media
  duration INTERVAL, -- the length of the broadcast
  episode VARCHAR (255) -- whether or not the studio has a copy of the broadcast
);