/* 
This is a SQL table for the media that feature the artist Christian Johnson and his work.
 */

CREATE TABLE media (
-- * METADATA
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

-- * media
title VARCHAR (255) NOT NULL,
type media_type NOT NULL,
release_date DATE NOT NULL,
URL VARCHAR (255) NOT NULL,
language VARCHAR (255) DEFAULT 'english' NOT NULL,
have_copy BOOLEAN NOT NULL DEFAULT FALSE,
)