--* The images table is designed to store metadata and information about various images, including their URLs, the dates they were taken, and who took them. It also includes fields for usage rights and any additional notes related to the images.

CREATE TABLE images (
  -- * METADATA
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- * IMAGE
  url VARCHAR (255) NOT NULL, -- url to image
  date_image DATE, -- date image was taken
  image_by VARCHAR (255), -- photographer
  image_by_url VARCHAR (255), -- url for photographer
  usage_rights VARCHAR (255),
  notes TEXT
);

-- Path: tables/images/images.sql


